cookie:
  expiry_days: 30
  key: focus_flow_engagement_monitor_secret_key_2024
  name: focus_flow_auth_cookie
credentials:
  usernames:
    admin:
      email: admin@focusflow.app
      name: Administrator
      password: $2b$12$JulP5jIW557cpezUHh02fu088EBA3brJfQKLM.vjc1kdcNxVUWes2 # password is 'admin123'
preauthorized:
  emails:
    - admin@focusflow.app
